/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddProcess: typeof import('./src/components/admin/AddProcess.vue')['default']
    ChangeGroup: typeof import('./src/components/admin/ChangeGroup.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GroupScores: typeof import('./src/components/teacher/GroupScores.vue')['default']
    PeojectTitleExcle: typeof import('./src/components/admin/PeojectTitleExcle.vue')['default']
    ProcessScore: typeof import('./src/components/teacher/ProcessScore.vue')['default']
    RestPassword: typeof import('./src/components/admin/RestPassword.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectStudent: typeof import('./src/components/teacher/SelectStudent.vue')['default']
    StartTime: typeof import('./src/components/admin/StartTime.vue')['default']
    StudentExcle: typeof import('./src/components/admin/StudentExcle.vue')['default']
    TeacherExcle: typeof import('./src/components/admin/TeacherExcle.vue')['default']
    TurtorSelection: typeof import('./src/components/student/TurtorSelection.vue')['default']
    UnSelectStudent: typeof import('./src/components/teacher/UnSelectStudent.vue')['default']
    UpdatePassword: typeof import('./src/components/UpdatePassword.vue')['default']
    UploadFile: typeof import('./src/components/student/UploadFile.vue')['default']
  }
}
